services:
  web:
    pull_policy: never
    image: safer-backend
    build: 
      context: .
      target: prod
      dockerfile: Dockerfile
    container_name: safer-web
    environment:
      - PYTHONPATH=/app/Projeto
      - DB_NAME=db-safer
      - DB_USER=admin
      - DB_PASSWORD=$af&r2o25
      - DB_HOST=db-safer.ch8kmqwykuch.us-east-2.rds.amazonaws.com  # Nome do serviço MySQL
      - DB_PORT=3306
    ports:
      - "8000:8000"
    command: |
      sh -c "
      python3 Projeto/manage.py makemigrations SAFERapp 
      python3 Projeto/manage.py migrate
      gunicorn --bind 0.0.0.0:8000 Projeto.wsgi:application
      "

