services:
  web:
    build: 
      context: .
      target: prod
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app/Projeto
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "8000:8000"
    command: |
      sh -c "
      python3 Projeto/manage.py makemigrations 
      python3 Projeto/manage.py migrate
      gunicorn --bind 0.0.0.0:8000 Projeto.wsgi:application
      "
    volumes:
      - ./Projeto:/app/Projeto
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
