# Generated by Django 5.1.4 on 2024-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Senha', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('RelacaoUFRPE', models.IntegerField(choices=[(1, 'Docente'), (2, 'Discente'), (3, 'Técnico'), (4, 'Terceirizado'), (5, 'Visitante')], default=5)),
            ],
        ),
    ]
