# Generated by Django 5.1.4 on 2025-01-23 00:29

import SAFERapp.beans.Informativos
import SAFERapp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Autor', models.CharField(max_length=100)),
                ('Celular_Autor', models.CharField(max_length=20)),
                ('Telefone_Autor', models.CharField(max_length=20)),
                ('Relacao_Autor', models.CharField(choices=[('docente', 'Docente'), ('discente', 'Discente'), ('tecnico', 'Técnico'), ('terceirizado', 'Terceirizado'), ('visitante', 'Visitante')], default='visitante', max_length=20, verbose_name='Relação com a UFRPE')),
                ('Tipo_Caso', models.CharField(choices=[('presenca', 'Presença'), ('intervencao', 'Intervenção')], default='presenca', max_length=20, verbose_name='Tipo do caso')),
                ('Descricao', models.TextField()),
                ('Nome_Animal', models.CharField(max_length=100)),
                ('Local', models.CharField(choices=[('ru', 'RU'), ('trasrural', 'Transrural'), ('biblioteca_central', 'Biblioteca Central'), ('biblioteca_setorial', 'Biblioteca Setorial'), ('ceagri', 'CEAGRI'), ('cegoe', 'CEGOE'), ('dep_medicina_vet', 'Departamento de Medicina Veterinária'), ('dep_zootecnia', 'Departamento de Zootecnia'), ('pred_central', 'Prédio Central'), ('oref_rural', 'Prefeitura da UFRPE')], default='ru', max_length=20, verbose_name='Local do caso')),
                ('Referencia', models.CharField(max_length=100)),
                ('DataHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em análise'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status do chamado')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='imagens/')),
                ('IdOcorrencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Imagens_registradas', to='SAFERapp.ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, verbose_name='Telefone Fixo')),
                ('relacao_ufrpe', models.CharField(choices=[('docente', 'Docente'), ('discente', 'Discente'), ('tecnico', 'Técnico'), ('terceirizado', 'Terceirizado'), ('visitante', 'Visitante')], default='visitante', max_length=20, verbose_name='Relação com a UFRPE')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('analista', 'Analista'), ('comum', 'Comum')], default='comum', max_length=20, verbose_name='Tipo de Usuário')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', SAFERapp.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_analizadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista responsável'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id_informativo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_informativo', models.CharField(max_length=100, verbose_name='Título do Informativo')),
                ('corpo_informativo', models.TextField(default='Sem corpo', verbose_name='Corpo do Informativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('id_Autor', models.ForeignKey(default=SAFERapp.models.get_or_create_anonymous_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Autor do Informativo')),
            ],
        ),
    ]
