# Generated by Django 5.1.4 on 2024-12-18 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAFERapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='DataHora',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 23, 22, 51, 157363)),
        ),
    ]
