# Generated by Django 5.1.4 on 2024-12-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAFERapp', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='Celular_Autor',
            field=models.CharField(default=99999999999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Nome_Animal',
            field=models.CharField(default='desconecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Nome_Autor',
            field=models.CharField(default='Jorge', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Referencia',
            field=models.CharField(default='ref', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Relacao_Autor',
            field=models.CharField(choices=[('docente', 'Docente'), ('discente', 'Discente'), ('tecnico', 'Técnico'), ('terceirizado', 'Terceirizado'), ('visitante', 'Visitante')], default='visitante', max_length=20, verbose_name='Relação com a UFRPE'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Telefone_Autor',
            field=models.CharField(default=9999999999999999999999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='Tipo_Caso',
            field=models.CharField(choices=[('presenca', 'Presença'), ('intervencao', 'Intervenção')], default='presenca', max_length=20, verbose_name='Tipo do caso'),
        ),
    ]
